# Translate some inputs from web scraping from Portuguese to English

def translate(input)
  # Translate Code Here
  if input == "Vestuário"
    "Clothing"
  elsif input == "Livros"
    "Books"
  elsif input == "Decoração"
    "Decoration"
  elsif input == "Cozinha"
    "Kitchen"
  elsif input == "Acessórios"
    "Accessories"
  elsif input == "Colecionáveis"
    "Colectibles"
  elsif input == "Camisetas"
    "Shirts"
  elsif input == "Bonés"
    "Hats"
  elsif input == "Calçados"
    "Shoes"
  elsif input == "Colares"
    "Necklaces"
  elsif input == "Máscaras de Dormir"
    "Masks - Sleeping"
  elsif input == "Máscaras Nerd de Tecido"
    "Masks - Nerd Clothing"
  elsif input == "Máscara Preta"
    "Masks - Black"
  elsif input == "Meias"
    "Socks"
  elsif input == "Moletons"
    "Hoodies"
  elsif input == "Apocalipse Zumbi"
    "Zombies"
  elsif input == "Aventura"
    "Adventure"
  elsif input == "Contos"
    "Tales"
  elsif input == "Crônicas"
    "Chronicles"
  elsif input == "Ficção Científica"
    "Science Fiction"
  elsif input == "Guerra"
    "War"
  elsif input == "Almofadas"
    "Pillows"
  elsif input == "Almofadas de Pescoço"
    "Neck Pillows"
  elsif input == "Almofadas Exclusivas"
    "Exclusive Pillows"
  elsif input == "Cabideiros"
    "Cloth Hangers"
  elsif input == "Caixas Organizadoras"
    "Box Organizer"
  elsif input == "Capachos"
    "Rugs"
  elsif input == "Cofres"
    "Safes"
  elsif input == "Decoração Nerd"
    "Nerd Decoration"
  elsif input == "Luminárias"
    "Lamps"
  elsif input == "Abridores e cortadores"
    "Bottle Openers and Cutters"
  elsif input == "Aventais"
    "Aprons"
  elsif input == "Bandejas"
    "Trays"
  elsif input == "Canecas"
    "Coffee Mugs"
  elsif input == "Copos"
    "Cups"
  elsif input == "Cozinha Nerd"
    "Nerd Kitchen"
  elsif input == "Jogos Americanos"
    "Placemats"
  elsif input == "Luvas"
    "Gloves"
  elsif input == "De R$5,00 até R$20,00"
    "From CDN$5.00 to CDN$20.00"
  elsif input == "De R$20,00 até R$40,00"
    "From CDN$20.00 to CDN$40.00"
  elsif input == "De R$40,00 até R$80,00"
    "From CDN$40.00 to CDN$80.00"
  elsif input == "De R$80,00 até R$150,00"
    "From CDN$80.00 to CDN$150.00"
  elsif input == "Acima de R$150,00"
    "More than CDN$150.00"
  else
    input
  end
end

# Falta: Todas as marcas
